['rs_bikemechanic_tablet'] = { client={image='rs_bikemechanic_tablet.png'}, label='RS Bike Mechanic tablet', weight=900, stack=false, close=true },
['rs_moto_engine_oil'] = { client={image='rs_moto_engine_oil.png'}, label='Motorolie', weight=750, stack=true, close=true },
['rs_moto_spark_plugs'] = { client={image='rs_moto_spark_plugs.png'}, label='Bougies', weight=250, stack=true, close=true },
['rs_moto_brake_pads'] = { client={image='rs_moto_brake_pads.png'}, label='Motor remblokken', weight=600, stack=true, close=true },
['rs_moto_chain'] = { client={image='rs_moto_chain.png'}, label='Motorketting', weight=1400, stack=true, close=true },
['rs_moto_tire_set'] = { client={image='rs_moto_tire_set.png'}, label='Motorbandenset', weight=2500, stack=true, close=true },
['rs_moto_battery'] = { client={image='rs_moto_battery.png'}, label='Motoraccu', weight=1800, stack=true, close=true },
['rs_moto_clutch_cable'] = { client={image='rs_moto_clutch_cable.png'}, label='Koppelingskabel', weight=350, stack=true, close=true },
['rs_moto_turbo_kit'] = { client={image='rs_moto_turbo_kit.png'}, label='Motor turbo kit', weight=3200, stack=true, close=true },
['rs_moto_ecu'] = { client={image='rs_moto_ecu.png'}, label='Race ECU', weight=450, stack=true, close=true },
['rs_moto_sport_exhaust'] = { client={image='rs_moto_sport_exhaust.png'}, label='Sportuitlaat', weight=2600, stack=true, close=true },
['rs_moto_race_brakes'] = { client={image='rs_moto_race_brakes.png'}, label='Race-remmenset', weight=1800, stack=true, close=true },
['rs_moto_race_transmission'] = { client={image='rs_moto_race_transmission.png'}, label='Race-transmissie', weight=2800, stack=true, close=true },
['rs_moto_sport_suspension'] = { client={image='rs_moto_sport_suspension.png'}, label='Sportvering', weight=2200, stack=true, close=true },
['rs_moto_antilag_software'] = { client={image='rs_moto_antilag_software.png'}, label='Antilag software', weight=150, stack=true, close=true },
['rs_moto_launch_control'] = { client={image='rs_moto_launch_control.png'}, label='2-step launch control', weight=150, stack=true, close=true },
['rs_moto_stage2_software'] = { client={image='rs_moto_stage2_software.png'}, label='Stage 2 software', weight=150, stack=true, close=true }
