['rs_bikemechanic_tablet'] = { client={image='rs_bikemechanic_tablet.svg'}, label='RS Bike Mechanic tablet', weight=900, stack=false, close=true },
['rs_moto_engine_oil'] = { client={image='rs_moto_engine_oil.svg'}, label='Motorolie', weight=750, stack=true, close=true },
['rs_moto_spark_plugs'] = { client={image='rs_moto_spark_plugs.svg'}, label='Bougies', weight=250, stack=true, close=true },
['rs_moto_brake_pads'] = { client={image='rs_moto_brake_pads.svg'}, label='Motor remblokken', weight=600, stack=true, close=true },
['rs_moto_chain'] = { client={image='rs_moto_chain.svg'}, label='Motorketting', weight=1400, stack=true, close=true },
['rs_moto_tire_set'] = { client={image='rs_moto_tire_set.svg'}, label='Motorbandenset', weight=2500, stack=true, close=true },
['rs_moto_battery'] = { client={image='rs_moto_battery.svg'}, label='Motoraccu', weight=1800, stack=true, close=true },
['rs_moto_clutch_cable'] = { client={image='rs_moto_clutch_cable.svg'}, label='Koppelingskabel', weight=350, stack=true, close=true },
['rs_moto_turbo_kit'] = { client={image='rs_moto_turbo_kit.svg'}, label='Motor turbo kit', weight=3200, stack=true, close=true },
['rs_moto_ecu'] = { client={image='rs_moto_ecu.svg'}, label='Race ECU', weight=450, stack=true, close=true },
['rs_moto_sport_exhaust'] = { client={image='rs_moto_sport_exhaust.svg'}, label='Sportuitlaat', weight=2600, stack=true, close=true },
['rs_moto_race_brakes'] = { client={image='rs_moto_race_brakes.svg'}, label='Race-remmenset', weight=1800, stack=true, close=true },
['rs_moto_race_transmission'] = { client={image='rs_moto_race_transmission.svg'}, label='Race-transmissie', weight=2800, stack=true, close=true },
['rs_moto_sport_suspension'] = { client={image='rs_moto_sport_suspension.svg'}, label='Sportvering', weight=2200, stack=true, close=true },
['rs_moto_antilag_software'] = { client={image='rs_moto_antilag_software.svg'}, label='Antilag software', weight=150, stack=true, close=true },
['rs_moto_launch_control'] = { client={image='rs_moto_launch_control.svg'}, label='2-step launch control', weight=150, stack=true, close=true },
['rs_moto_stage2_software'] = { client={image='rs_moto_stage2_software.svg'}, label='Stage 2 software', weight=150, stack=true, close=true }
